[workspace]
authors = ["Mason McGill <mason.b.mcgill@gmail.com>"]
channels = ["conda-forge"]
name = "flybody-tutorial"
platforms = ["linux-64", "osx-arm64", "win-64"]
version = "0.1.0"

[dependencies]
python = "3.11.*"
ffmpeg = ">=7.1.1,<8"

[pypi-dependencies]
matplotlib = ">=3.10.3, <4"
mujoco = "==3.3.3"
pillow = ">=11.2.1, <12"
h5py = ">=3.14.0, <4"
ipykernel = ">=6.29.5, <7"
notebook = ">=7.4.3, <8"
scipy = ">=1.16.0, <2"
numpy = ">=2.3.1, <3"
onnx = ">=1.18.0, <2"
onnxruntime = ">=1.22.0, <2"
rich = ">=14.0.0, <15"
